# Site settings
title:          TILBlog
description:    "기술블로그"
baseurl:        ""
url:            "https://chesterhow.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         ReneeKim  
  url:          https://chester.how
  email:        jhjin2u@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
theme:      
permalink:      /:year-:month-:day/:title
paginate:       5
